// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xea5a8c37a1dc24de");
export const RideableType = {
	UNKNOWN_RIDEABLE_TYPE: 0,
	ELECTRIC_BIKE: 1,
	CLASSIC_BIKE: 2,
} as const;
export type RideableType = (typeof RideableType)[keyof typeof RideableType];
export const MemberCasual = {
	UNKNOWN_MEMBER_CASUAL: 0,
	MEMBER: 1,
	CASUAL: 2,
} as const;
export type MemberCasual = (typeof MemberCasual)[keyof typeof MemberCasual];
export class Trip extends $.Struct {
	static readonly _capnp = {
		displayName: "Trip",
		id: "923fdeee6e7a9a4d",
		size: new $.ObjectSize(56, 5),
	};
	get rideId(): string {
		return $.utils.getText(0, this);
	}
	set rideId(value: string) {
		$.utils.setText(0, value, this);
	}
	get rideableType(): RideableType {
		return $.utils.getUint16(0, this) as RideableType;
	}
	set rideableType(value: RideableType) {
		$.utils.setUint16(0, value, this);
	}
	get startedAtMs(): bigint {
		return $.utils.getInt64(8, this);
	}
	set startedAtMs(value: bigint) {
		$.utils.setInt64(8, value, this);
	}
	get endedAtMs(): bigint {
		return $.utils.getInt64(16, this);
	}
	set endedAtMs(value: bigint) {
		$.utils.setInt64(16, value, this);
	}
	get startStationName(): string {
		return $.utils.getText(1, this);
	}
	set startStationName(value: string) {
		$.utils.setText(1, value, this);
	}
	get startStationId(): string {
		return $.utils.getText(2, this);
	}
	set startStationId(value: string) {
		$.utils.setText(2, value, this);
	}
	get endStationName(): string {
		return $.utils.getText(3, this);
	}
	set endStationName(value: string) {
		$.utils.setText(3, value, this);
	}
	get endStationId(): string {
		return $.utils.getText(4, this);
	}
	set endStationId(value: string) {
		$.utils.setText(4, value, this);
	}
	get startLat(): number {
		return $.utils.getFloat64(24, this);
	}
	set startLat(value: number) {
		$.utils.setFloat64(24, value, this);
	}
	get startLng(): number {
		return $.utils.getFloat64(32, this);
	}
	set startLng(value: number) {
		$.utils.setFloat64(32, value, this);
	}
	get endLat(): number {
		return $.utils.getFloat64(40, this);
	}
	set endLat(value: number) {
		$.utils.setFloat64(40, value, this);
	}
	get endLng(): number {
		return $.utils.getFloat64(48, this);
	}
	set endLng(value: number) {
		$.utils.setFloat64(48, value, this);
	}
	get memberCasual(): MemberCasual {
		return $.utils.getUint16(2, this) as MemberCasual;
	}
	set memberCasual(value: MemberCasual) {
		$.utils.setUint16(2, value, this);
	}
	toString(): string {
		return "Trip_" + super.toString();
	}
}
export class ServerResponseAll extends $.Struct {
	static readonly _capnp = {
		displayName: "ServerResponseAll",
		id: "af9b587efc9700d0",
		size: new $.ObjectSize(0, 1),
	};
	static _Trips: $.ListCtor<Trip>;
	_adoptTrips(value: $.Orphan<$.List<Trip>>): void {
		$.utils.adopt(value, $.utils.getPointer(0, this));
	}
	_disownTrips(): $.Orphan<$.List<Trip>> {
		return $.utils.disown(this.trips);
	}
	get trips(): $.List<Trip> {
		return $.utils.getList(0, ServerResponseAll._Trips, this);
	}
	_hasTrips(): boolean {
		return !$.utils.isNull($.utils.getPointer(0, this));
	}
	_initTrips(length: number): $.List<Trip> {
		return $.utils.initList(0, ServerResponseAll._Trips, length, this);
	}
	set trips(value: $.List<Trip>) {
		$.utils.copyFrom(value, $.utils.getPointer(0, this));
	}
	toString(): string {
		return "ServerResponseAll_" + super.toString();
	}
}
ServerResponseAll._Trips = $.CompositeList(Trip);
